heading_main_title = 'Ahmer\'s Automaticalling And Silently Software Installation Program'
heading_developer = 'Developer'
heading_internet = 'Internet'
heading_major = 'Major'
heading_mobile = 'Mobile'
heading_multimedia = 'Multimedia'
heading_pdf = 'PDF'
heading_utilities = 'Utilities'
heading_zero = 'Value must be greater than zero'

__author__ = 'Ahmer Afzal'
__company__ = 'Rose Corporation'
__copyright__ = 'Copyright (c) 2016 - 2020, ' + __company__
__desription__ = 'Ahmer\'s Auto Silently Installation Program'
__email__ = 'ahmerafzal@yahoo.com'
__product__ = 'InstallMySofts'
__version__ = '1.1.8'
